/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2018-07-05 07:56:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registration2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Travel Agency a Travel Agency Category Flat Bootstrap Responsive Website Template | Booking :: w3layouts</title>\r\n");
      out.write("<!-- custom-theme -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Travel Agency Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n");
      out.write("\t\tfunction hideURLbar(){ window.scrollTo(0,1); } </script>\t\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- For Testimonials slider -->\r\n");
      out.write("<!-- //For Testimonials slider -->\r\n");
      out.write("<!-- //custom-theme files-->\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- //custom-theme files-->\r\n");
      out.write("<!-- font-awesome-icons -->\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("<!-- //font-awesome-icons -->\r\n");
      out.write("<!-- googlefonts -->\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,vietnamese\" rel=\"stylesheet\">\r\n");
      out.write("<!-- //googlefonts -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery-ui.css\" />\r\n");
      out.write("<link href=\"css/bookingstyle.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- banner -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Top-Bar -->\r\n");
      out.write("\t\t\t\t<div class=\"top\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6 top-middle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6 top-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-mobile\" aria-hidden=\"true\"></i> +021 365 777</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><i class=\"fa fa-map-marker\" aria-hidden=\"true\"></i> JB Tower, Near SAL Hospital </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"top-bar\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"navbar-header navbar-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1><a class=\"navbar-brand\" href=\"index.html\">Trip Planner</span></a></h1>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"collapse navbar-collapse navbar-right\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<nav class=\"cl-effect-15\" id=\"cl-effect-15\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"about.jsp\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"booking.jsp\">Booking</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"gallery.jsp\">Gallery</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"package.jsp\">Packages</a></li>\r\n");
      out.write("                                                    <li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-hover=\"Pages\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Pages <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"icons.html\">Icons</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"typography.html\">Typography</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //Top-Bar -->\r\n");
      out.write("\t\t<!-- w3-banner -->\r\n");
      out.write("\t<div class=\"banner-1\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //banner -->\r\n");
      out.write("<!-- main-section -->\r\n");
      out.write("\t<div class=\"head agile\" style=\"margin-left: 50px\">\r\n");
      out.write("\t<div class=\"wthree_head_section\">\r\n");
      out.write("\t\t\t\t<h3 class=\"w3l_header\">Register Yourself</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div class=\"login w3\">\r\n");
      out.write("\t\t\t<div class=\"sap_tabs resp-tabs-list\">\r\n");
      out.write("\t\t\t\t<div id=\"horizontalTab\" style=\"display: block; width: 100%; margin: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t \r\n");
      out.write("\t\t\t\t\t<div class=\"container\" style=\"margin-right: 50px\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-1 content\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-top agileinfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2></h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <form action=\"registrationservlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"w3_agileits_main_grid w3l_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Name * </h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"name\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"First name\" placeholder=\"Your Name\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"w3_agileits_main_grid w3l_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>E-mail </h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"Email\" placeholder=\"ex : yourmail@gmail.com\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"fromtop\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_main_grid held\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>From*</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"category1\" name=\"category1\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category1\">Australia</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">Singapore</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">America</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">London</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Goa</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Canada</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Srilanka</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>To*</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"category1\" name=\"category1\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">Singapore</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category1\">Australia</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">America</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">London</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Goa</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Canada</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Srilanka</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_main_grid w3_agileits_main_grid held\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"wthree_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>Adults*</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"category1\" name=\"category1\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category1\">01</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">02</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">03</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category4\">04</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">05</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">06</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>Children*</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"category1\" name=\"category1\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category1\">00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">01</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">02</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category4\">03</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">04</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">05</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category4\">06</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_main_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_grid mim\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>Travel Class*</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"category2\" name=\"category1\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category1\">Economy class</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">Premium Economy</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Business class</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">First Class</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_grid w3ls_main_grid agileinfo_main_grid held\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Departure On*</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"date\" id=\"datepicker\" name=\"Text\" type=\"text\" value=\"mm/dd/yyyy\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = '08/13/2016';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>Journey type*</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"category1\" name=\"category1\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category1\">One Way</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">Round trip</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"aitssubmitw3ls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"process.jsp\">  \r\n");
      out.write("<input type=\"text\" name=\"uname\" value=\"Name...\" onclick=\"this.value=''\"/><br/>  \r\n");
      out.write("<input type=\"text\" name=\"uemail\"  value=\"Email ID...\" onclick=\"this.value=''\"/><br/>  \r\n");
      out.write("<input type=\"password\" name=\"upass\"  value=\"Password...\" onclick=\"this.value=''\"/><br/>  \r\n");
      out.write("<input type=\"submit\" value=\"register\"/>  \r\n");
      out.write("</form>  \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-1 resp-tab-content\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-top agileits\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Search for Trains</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w3layouts-agileits\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"w3layoutscontactagileits\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"w3_agileits_main_grid w3l_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h5>Name * </h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"First name\" placeholder=\"Your Name\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"w3_agileits_main_grid w3l_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h5>E-mail </h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"Email\" placeholder=\"ex : yourmail@gmail.com\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_main_grid w3_agileits_main_grid held\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"wthree_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>Route</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"category\" name=\"category\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"none\">None</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category1\">Local</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">Non-local</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>Number of Passengers*</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"category1\" name=\"category1\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category1\">01</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">02</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">03</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category4\">04</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">05</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">06</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_main_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>Day*</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"category2\" name=\"category1\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category1\">Sunday</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">Monday</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Tuesday</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Wednesday</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Thursday</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Friday</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Saturday</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"fromtop\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_main_grid held\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>From*</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"category1\" name=\"category1\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category1\">Australia</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">Singapore</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">America</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">London</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Goa</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Canada</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Srilanka</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>To*</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"category1\" name=\"category1\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">Singapore</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category1\">Australia</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">America</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">London</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Goa</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Canada</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Srilanka</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"aitssubmitw3ls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-1 resp-tab-content\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-top agileits\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Search for Hotels</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w3layouts_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\" class=\"w3_form_post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"w3_agileits_main_grid w3l_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>Name * </h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"nam\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"First name\" placeholder=\"First Name\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"nam1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"Last name\" placeholder=\"Last Name\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"w3_agileits_main_grid w3l_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>E-mail </h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"Email\" placeholder=\"ex : yourmail@gmail.com\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_main_grid w3_agileits_main_grid held\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"wthree_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>Room Type</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"category\" name=\"category\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"none\">None</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category1\">Single Room</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">Double Room</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">Suit Room</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5>Number of Guests *</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"category1\" name=\"category1\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category1\">01</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">02</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">03</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category4\">04</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category2\">05</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"category3\">06</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_grid w3ls_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Check In &amp; Time *</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_gridl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"date\" id=\"datepicker\" name=\"Text\" type=\"text\" value=\"mm/dd/yyyy\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = '08/13/2016';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_gridr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"time\" name=\"Time\" placeholder=\" \" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_grid w3ls_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Check Out &amp; Time *</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_gridl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"date\" id=\"datepicker1\" name=\"Text\" type=\"text\" value=\"mm/dd/yyyy\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = '08/13/2016';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_gridr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"time\" name=\"Time\" placeholder=\" \" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"w3_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"w3_main_grid_right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-1 resp-tab-content\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-top agileinfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>Search for Cabs</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"containerw3layouts-agileits\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"w3layoutscontactagileits\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"w3_agileits_main_grid w3l_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h5>Name * </h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"First name\" placeholder=\"Your Name\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"w3_agileits_main_grid w3l_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h5>E-mail </h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"Email\" placeholder=\"ex : yourmail@gmail.com\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"aitsphonew3ls agileinfow3ls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"aitsphonew3ls-lable wthreelable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Phone</label><span class=\"colon\">:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"aitsphonew3ls-input wthreeinput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Area Code</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"agilecode\" type=\"tel\" pattern=\"[\\+]\\d{2}[\\(]\\d{2}[\\)]\\d{4}[\\-]\\d{4}\" title=\"Phone Number (Format: +99(99)9999-9999)\" name=\"Area Code\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"aitsnumber\">Number</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"wthreeland\" type=\"tel\" pattern=\"[\\+]\\d{2}[\\(]\\d{2}[\\)]\\d{4}[\\-]\\d{4}\" title=\"Phone Number (Format: +99(99)9999-9999)\" name=\"Number\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_grid w3ls_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Departure date &amp; Time *</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_gridl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"date\" id=\"datepicker1\" name=\"Text\" type=\"text\" value=\"Date\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = '08/13/2016';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_gridr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"time\" name=\"Time\" placeholder=\" \" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_grid w3ls_main_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileinfo_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>Return date &amp; Time *</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_gridl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"date\" id=\"datepicker1\" name=\"Text\" type=\"text\" value=\"date\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = '08/13/2016';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_gridr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"time\" name=\"Time\" placeholder=\" \" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"aitspickupaddress agileinfow3ls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"aitspickupaddress-lable wthreelable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"agilepickup-lable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Pickup</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Address</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"colon\">:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"aitspickupaddress-input wthreeinput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea name=\"Pickup Address\" placeholder=\"Pickup Address\" required=\"\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"aitsdestinationaddress agileinfow3ls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"aitsdestinationaddress-lable wthreelable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"agiledest-lable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Destination</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Address</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"colon\">:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"aitsdestinationaddress-input wthreeinput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea name=\"Destination Address\" placeholder=\"Destination Address\" required=\"\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"w3lsjourneyaits agileinfow3ls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"w3lsjourneyaits-lable wthreelable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"aitsjourney-lable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Journey</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Type</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"colon\">:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"w3lsjourneyaits-input wthreeinput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"journey\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"single\">Single</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"two way\">Round Trip</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"aitssubmitw3ls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("<!-- //main-section -->\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"col-md-4 agile_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>Contact Info</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_address\">\r\n");
      out.write("\t\t\t\t\t<li><i class=\"glyphicon glyphicon-map-marker\" aria-hidden=\"true\"></i>1234k Avenue, 4th block, <span>New York City.</span></li>\r\n");
      out.write("\t\t\t\t\t<li><i class=\"glyphicon glyphicon-envelope\" aria-hidden=\"true\"></i><a href=\"mailto:info@example.com\">info@example.com</a></li>\r\n");
      out.write("\t\t\t\t\t<li><i class=\"glyphicon glyphicon-earphone\" aria-hidden=\"true\"></i>+1234 567 567</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 agile_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>About Us</h3>\r\n");
      out.write("\t\t\t\t<p>Donec purus neque, vulputate id est id, pretium semper enim. Morbi viverra \r\n");
      out.write("\t\t\t\t\tcongue nisi vel pulvinar posuere sapien eros, sed faucibus.</p>\r\n");
      out.write("\t\t\t\t<ul class=\"agileits_social_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"w3_agile_facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"agile_twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"w3_agile_dribble\"><i class=\"fa fa-dribbble\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 agile_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>Latest News</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"agileits_w3layouts_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">Donec purus neque, vulputate \r\n");
      out.write("\t\t\t\t\t\t\tid est id</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">Nullam fringilla sed quam vitae</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">Cras libero arcu, accumsan ac </a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">Aenean porttitor accumsan</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal\">Nullam sed turpis gravida</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t<div class=\"w3_agileits_footer_grids\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 wthree_footer_grid_right\">\r\n");
      out.write("\t\t\t\t\t<h3>Sign up for our Newsletter</h3>\r\n");
      out.write("\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"email\" name=\"Email\" placeholder=\"Enter your email...\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"agileinfo_copyright\">\r\n");
      out.write("\t\t<p>© 2018 Travel Agency. All rights reserved | Design by <a href=\"http://w3layouts.com/\">W3layouts</a></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //footer -->\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap-modal-pop-up -->\r\n");
      out.write("\t<div class=\"modal video-modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModal\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\tTravel Agency\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/1.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t<p>Ut enim ad minima veniam, quis nostrum \r\n");
      out.write("\t\t\t\t\t\t\texercitationem ullam corporis suscipit laboriosam, \r\n");
      out.write("\t\t\t\t\t\t\tnisi ut aliquid ex ea commodi consequatur? Quis autem \r\n");
      out.write("\t\t\t\t\t\t\tvel eum iure reprehenderit qui in ea voluptate velit \r\n");
      out.write("\t\t\t\t\t\t\tesse quam nihil molestiae consequatur, vel illum qui \r\n");
      out.write("\t\t\t\t\t\t\tdolorem eum fugiat quo voluptas nulla pariatur.\r\n");
      out.write("\t\t\t\t\t\t\t<i>\" Quis autem vel eum iure reprehenderit qui in ea voluptate velit \r\n");
      out.write("\t\t\t\t\t\t\t\tesse quam nihil molestiae consequatur.</i></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //bootstrap-modal-pop-up --> \r\n");
      out.write("<!-- js -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("\t<!-- for bootstrap working -->\r\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\t<!-- //for bootstrap working -->\r\n");
      out.write("<!-- //js -->\r\n");
      out.write("<!-- //here starts scrolling icon -->\r\n");
      out.write("<script src=\"js/SmoothScroll.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("\t<!-- here stars scrolling script -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\t\tvar defaults = {\r\n");
      out.write("\t\t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t$().UItoTop({ easingType: 'easeOutQuart' });\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //here ends scrolling script -->\r\n");
      out.write("<!-- //here ends scrolling icon -->\r\n");
      out.write("\r\n");
      out.write("<!-- scrolling script -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t$(\".scroll\").click(function(event){\t\t\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script> \r\n");
      out.write("<!-- //scrolling script -->\r\n");
      out.write("<!-- //Calendar -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<script src=\"js/jquery-ui.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  $(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t$( \"#datepicker,#datepicker1\" ).datepicker();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  });\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  </script>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- //Calendar -->\r\n");
      out.write("<!--script-->\r\n");
      out.write("<script src=\"js/easyResponsiveTabs.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t    <script type=\"text/javascript\">\r\n");
      out.write("\t\t\t    $(document).ready(function () {\r\n");
      out.write("\t\t\t        $('#horizontalTab').easyResponsiveTabs({\r\n");
      out.write("\t\t\t            type: 'default', //Types: default, vertical, accordion           \r\n");
      out.write("\t\t\t            width: 'auto', //auto or any width like 600px\r\n");
      out.write("\t\t\t            fit: true   // 100% fit in a container\r\n");
      out.write("\t\t\t        });\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</script>\t\r\n");
      out.write("<!--script-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
